# Daily update
name: ecdc_update

# Controls when the action will run
# Every minute, to test it out
on:
  schedule:
    - cron:  '* * * * *'

jobs: 
  plot:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          
    # Load repo and install R
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("ggplot2")'
        R -e 'install.packages("scales")'
    # Run R script
    - name: Make plot
      run: Rscript ecdc-trend/covid19be-ecdc-trends.R
      
    # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add ecdc-trend/*
        git commit -am "update $(date)"
        git push origin master
