# Daily update
name: ecdc_update

# Controls when the action will run
on:
  schedule:
    - cron:  '20 04 * * *'
  workflow_dispatch:
  
jobs: 
  plot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Default settings
    defaults:
      run:
        working-directory: ./ecdc-trend
        
    # Load repo and install R and pandoc
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v1

    # Set-up R
    - name: Install packages
      run: |
        Rscript -e 'install.packages("ggplot2")'
        Rscript -e 'install.packages("scales")'
        Rscript -e 'install.packages("rmarkdown")'
        Rscript -e 'install.packages("knitr")'
      
    # Run R script
    - name: Make plot
      run: Rscript covid19be-ecdc-trends.R

    # Add new files in data folder, commit along with other modified files, push
    - uses: stefanzweifel/git-auto-commit-action@v4.6.0
      with:
        commit_message: "update situation"
